version: '3.9'

networks:
  ms-network:
    driver: bridge

services:

  mongodb:
    image: mongo
    container_name: stockinformations-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: 'stockinformations'
    networks:
      - ms-network

  document-service:
    build: ./DocumentService
    restart: on-failure
    ports:
      - "9010:9010"
    networks:
      - ms-network

  mail-service:
    build: ./MailService
    restart: on-failure
    ports:
      - "9020:9020"
    #    depends_on:
    #      - mongodb
    networks:
      - ms-network


  stock-analysis-service:
    build: ./StockAnalysisService
    restart: on-failure
    ports:
      - "9030:9030"
    #    depends_on:
    #      - mongodb
    networks:
      - ms-network

  stock-web-scraping-service:
    build: StockWebScrapingServiceNew
    restart: on-failure
    ports:
      - "9040:9040"
#    depends_on:
#      - mongodb
    networks:
      - ms-network


  user-service:
    build: ./UserService
    restart: on-failure
    ports:
      - "9050:9050"
    #    depends_on:
    #      - mongodb
    networks:
      - ms-network