version: '3.9'

networks:
  ms-network:
    driver: bridge

services:
#  postgres:
#    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: password
#    networks:
#      - ms-network

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "9094:9094"
#    command:
#      - 'php'
#      - '-S'
#      - '[::]:9094'
#      - '-t'
#      - '/var/www/html'
#    entrypoint:
#      - 'entrypoint.sh'


#  keycloak:
#    image: jboss/keycloak
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#      DB_VENDOR: POSTGRES
#      DB_ADDR: postgres
#      DB_PORT: 5432
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_PASSWORD: password
#    depends_on:
#      - postgres
#    networks:
#      - ms-network



  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "stocks, users"
    volumes:
      - mongodb_data:/data/db

    networks:
      - ms-network

  document-service:
    build: ./DocumentService
    restart: on-failure
    ports:
      - "9010:9010"
#    depends_on:
#      - keycloak
    networks:
      - ms-network

  mail-service:
    build: ./MailService
    restart: on-failure
    ports:
      - "9020:9020"
    #    depends_on:
    #      - mongodb
    networks:
      - ms-network


  stock-analysis-service:
    build: ./StockAnalysisService
    restart: on-failure
    ports:
      - "9030:9030"
    #    depends_on:
    #      - mongodb
    networks:
      - ms-network

#  stock-web-scraping-service:
#    build: ./StockWebScrapingServiceNew
#    restart: on-failure
#    ports:
#      - "9040:9040"
##    depends_on:
##      - mongodb
#    networks:
#      - ms-network


  stock-web-scraping-service-py:
    build: ./StockWebScrapingServicePython
    restart: on-failure
    ports:
      - "9040:9040"
    #    depends_on:
    #      - mongodb
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ms-network

  user-service:
    build: ./UserService
    restart: on-failure
    ports:
      - "9050:9050"
    #    depends_on:
    #      - mongodb
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ms-network


volumes:
  mongodb_data:
  postgres_data:
    driver: local